[package]
name = "hifitime"
version = "3.4.1"
resolver = "2"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "Ultra-precise date and time handling in Rust for scientific applications with leap second support"
homepage = "https://nyxspace.com/MathSpec/time/"
documentation = "https://docs.rs/hifitime/"
repository = "https://github.com/nyx-space/hifitime"
keywords = ["date", "time", "science", "leap-second", "no-std"]
categories = ["date-and-time"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
serde = {version = "1.0.137", optional = true}
regex = {version = "1.5.5", optional = true}
serde_derive = {version = "1.0.137", optional = true}
der = {version = "0.6.0", features = ["derive", "real"], optional = true}
[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["libm"]

[dev-dependencies]
criterion = "0.4.0"

[features]
default = ["std"]
std = ["regex", "serde", "serde_derive"]
asn1der = ["der"]

[[bench]]
name = "bench_epoch"
harness = false
