[package]
name = "hifitime"
version = "3.0.0-beta.2"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "Ultra-precise date and time handling in Rust for scientific applications with leap second support"
homepage = "https://nyxspace.com/MathSpec/time/"
documentation = "https://docs.rs/hifitime/"
repository = "https://github.com/nyx-space/hifitime"
keywords = ["date", "time", "barycentric", "leap-second", "tai"]
categories = ["date-and-time"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
rand = "0.8.5"
rand_distr = "0.4.3"
regex = "1.5.4"
serde = "1.0.136"
serde_derive = "1.0.136"

[dev-dependencies]
serde_derive = "1.0.136"
criterion = "0.3.5"

[[bench]]
name = "bench_epoch"
harness = false
