[package]
name = "hifitime"
version = "2.3.2"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "Precise date and time handling in Rust built on top of TwoFloat with leap second support"
homepage = "https://nyxspace.com/MathSpec/time/"
documentation = "https://docs.rs/hifitime/"
repository = "https://github.com/nyx-space/hifitime"
keywords = ["date", "time", "barycentric", "leap-second", "tai"]
categories = ["date-and-time"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
rand = "0.8.0"
rand_distr = "0.4.0"
regex = "1.3.0"
serde = "1.0.0"
serde_derive = "1.0.0"
twofloat = "0.4.1"

[dev-dependencies]
serde_derive = "1.0.0"
criterion = "0.3.0"

[[bench]]
name = "bench_epoch"
harness = false