[package]
name = "hifitime"
version = "3.2.0-beta"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]
description = "Ultra-precise date and time handling in Rust for scientific applications with leap second support"
homepage = "https://nyxspace.com/MathSpec/time/"
documentation = "https://docs.rs/hifitime/"
repository = "https://github.com/nyx-space/hifitime"
keywords = ["date", "time", "science", "leap-second", "no-std"]
categories = ["date-and-time"]
readme = "README.md"
license = "Apache-2.0"

[dependencies]
serde = "1.0.137"
regex = {version = "1.5.5", optional = true}
serde_derive = {version = "1.0.137", optional = true}

[dev-dependencies]
criterion = "0.3.5"

[features]
default = ["std"]
std = ["regex", "serde_derive"]

[[bench]]
name = "bench_epoch"
harness = false
