on:
  pull_request:
  push:
    branches:
      - master

name: Formal Verification Workflow

jobs:

  formal-verif:
    name: Formal Verification
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Install Kani
        run: cargo install --locked kani-verifier && cargo-kani setup
      
      - name: Run Kani
        run: cargo kani
